export { default as AboutMe } from './AboutMe/AboutMe';
export * from './AboutMe/components';
export { default as FooterSection } from './Footer/FooterSection';
export { default as Hero } from './Hero/Hero';
export * from './Hero/components';
export { default as Home } from './Home';
export { default as Projects } from './Project/Projects';
export * from './Project/components';
export { default as Prueba2 } from './Prueba2';
export { default as StackSection } from './Stack/StackSection';
export { default as StackCardComponent } from './Stack/components/StackCardComponent';
export * from './index';
