export { default as GradientText } from './GradientText';
export { default as Hero } from './Hero/Hero';
export { default as AnchoreBox } from './Hero/components/AnchoreBox';
export { default as CardHeading } from './Hero/components/CardHeading';
export { default as HeadingHero } from './Hero/components/HeadingHero';
export * from './Icons';
export { default as Logo } from './Navbar/Components/Logo';
export { default as NavigationLinks } from './Navbar/Components/NavigationLinks';
export { default as Navbar } from './Navbar/Navbar';
export { default as Projects } from './Project/Projects';
export { default as ProjectCard } from './Project/components/ProjectCard';
export { default as SpinBox } from './Project/components/SpinBox';
export { default as Prueba2 } from './Prueba2';
export { default as PruebaPage } from './PruebaPage';
export * from './index';
